python hp_search.py \
    --sketch_model_name_or_path "klue/roberta-large" \
    --intensive_model_name_or_path "klue/roberta-large" \
    --do_train \
    --do_eval \
    --evaluation_strategy epoch \
    --logging_strategy epoch \
    --save_strategy epoch \
    --dataset_name "klue" \
    --dataset_path 'klue-mrc-v1.1' \
    --train_file 'klue-mrc-v1.1_train.json' \
    --validation_file 'klue-mrc-v1.1_dev.json' \
    --save_total_limit 1 \
    --output_dir outputs \
    --version_2_with_negative True \
    --num_train_epochs 5 \
    --logging_steps 100 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 16 \
    --metric_for_best_model eval_f1 \
    --fp16 \
    --load_best_model_at_end True